### ISSUE TITLE
Error on main hotkey (NoSuchMethodError: com.intellij.openapi.application.Application.invokeAndWait(Ljava/lang/Runnable;)V)

### ISSUE THREAD

**Issue by andreyvolokitin** [johnlindquist/AceJump#148]
AceJump 3.2.4, WebStorm 2016.2.4 Build #WS-162.2228.20, OS X. Full log:
`com.intellij.openapi.application.Application.invokeAndWait(Ljava/lang/Runnable;)V
java.lang.NoSuchMethodError: com.intellij.openapi.application.Application.invokeAndWait(Ljava/lang/Runnable;)V
	at com.johnlindquist.acejump.KeyboardHandler.activate(KeyboardHandler.kt:64)
	at com.johnlindquist.acejump.AceAction.actionPerformed(AceAction.kt:17)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:609)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by andreyvolokitin** [comment]
Works on WebStorm 2017.1.3 Build #WS-171.4424.63...

**Comment by esafirm** [comment]
Same here in Android Studio 2.3.2
```
com.intellij.openapi.application.Application.invokeAndWait(Ljava/lang/Runnable;)V
java.lang.NoSuchMethodError: com.intellij.openapi.application.Application.invokeAndWait(Ljava/lang/Runnable;)V
	at com.johnlindquist.acejump.KeyboardHandler.activate(KeyboardHandler.kt:64)
	at com.johnlindquist.acejump.AceAction.actionPerformed(AceAction.kt:17)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.ide.actions.GotoActionAction.lambda$performAction$1(GotoActionAction.java:273)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:73)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by breandan** [comment]
Possibly related: #143. Investigating, thanks for your patience. Did this error start to appear after updating to the latest version of AceJump (3.2.3+)?

**Comment by andreyvolokitin** [comment]
It was present in 3.2.0 AFAIK, definitely prior 3.2.3

**Comment by breandan** [comment]
Okay, I found the problem.* Should have a fix up shortly. Has AceJump been broken this whole time? :(

*Apparently [`invokeAndWait(Runnable)`](https://github.com/JetBrains/intellij-community/commit/712e22d01e0da0848f829d1bacee757deb94c2d7) as used [here](AceJump/src/main/kotlin/com/johnlindquist/acejump/KeyboardHandler.kt) is a fairly recent addition to the IntelliJ Platform API, which would explain why the error only appears on older versions of Android Studio / WebStorm, since they are based on an earlier version of the platform.

**Comment by sinlov** [comment]
I just roll back plugin version to `2.0.7`

https://github.com/johnlindquist/AceJump/releases/tag/2.0.7

 Just Older versions of IDEA not has `invokeAndWait(Runnable)` api

**Comment by breandan** [comment]
Should be fixed in the latest release. Please reopen if you encounter any issues. Thanks!
